var playlist = ["/mp3/BROODS - Sleep, Baby, Sleep.mp3",
"/mp3/Bang Gang - Forever Now.mp3",
"/mp3/Bang Gang - Out of Horizon.mp3",
"/mp3/Bang Gang,Keren Ann - A Lonely Bird (Featuring Keren Ann).mp3",
"/mp3/Befour - How Do You Do ？.mp3",
"/mp3/Belarus - In The End Its Easy.mp3",
"/mp3/Brianna - All I Need.mp3",
"/mp3/Brown Feather Sparrow - Great Art Thou.mp3",
"/mp3/Bruno Mars - Nothing On You (solo live).mp3",
"/mp3/Bryson Andres - Scabs.mp3",
"/mp3/Calvin Harris,Ellie Goulding - I Need Your Love.mp3",
"/mp3/Cam Kelley - Sketch Plane.mp3",
"/mp3/Capo Productions - Inspire.mp3",
"/mp3/Cascada - Blink (Video Edit).mp3",
"/mp3/Cassadee Pope - Good Times.mp3",
"/mp3/Celine Dion - All by Myself.mp3",
"/mp3/Childs - Mariana.mp3"];